# Generated by Django 4.0.5 on 2023-02-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_events_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='Durattion',
            new_name='Duration',
        ),
        migrations.AddField(
            model_name='events',
            name='Title',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
